### ISSUE TITLE
Use rfc7235-parser for authentication header parsing

### ISSUE THREAD

**Issue by raphinesse** [vMReal/digest-auth#22]
### I'm submitting a ...
[ ] bug report
[ ] feature request
[x] question about the decisions made in the repository
[ ] question about how to use this project

### Summary
I created a HTTP authentication header parser: [rfc7235-parser](https://github.com/raphinesse/rfc7235-parser). It can make your life easier 😉

### Other information
First off: thanks for creating this package. It's by far the best library I could find to implement a Digest authentication client in JS.

When evaluating various libraries for that purpose, one common theme emerged: all of these libraries had bugs when parsing the authentication headers. Some (e.g. this library) were better, some worse.

I decided that a proper parser for HTTP authentication headers would qualify as a library in it's own right. And since I could not find an existing one online, I went ahead and created one: [rfc7235-parser](https://github.com/raphinesse/rfc7235-parser). It's highlights include:
- supports all schemes that follow RFC 7235
- normalizes all case-insensitive parts (i.e. scheme and parameter names) to lowercase (like Node.js does with HTTP header field names)
- handles multiple schemes per header
- properly parses quoted parameter values

The docs are very minimal at the moment 😅. But together with the Typescript interface and the tests, it should hopefully be clear how it works.

If you're interested in using this library and you have any questions or feedback regarding it, please let me know.

**Comment by vMReal** [comment]
Thank you for your thanks!

On current, I am not considering a third-party library for parsing. There are many reasons for this

1. parse **and** generate are one of the main functions of this library. These functions should work the same and use the same code for it. It doesn't make any sense to use a third-party library for parsing but support generation myself

2. This library is highly specialized for solving 1 problem, and nothing more. So, the opportunity to parsed by many unnecessary schemes it is an extra function.

3. One of the priorities this library follows is trusting the security approach of this library. All business logic related to digest should be clear and keep on one place, without using third party library 

4. I also plan to expand the analysis logic, for example, validation (extend current lite DTO validation with more strict rules)

At the moment, the header parsing logic is fairly well covered by unit tests

In any case, it remains possible to use your own analysis implementation or expand the existing in your project
