### ISSUE TITLE
Missed dependency a `crypto` module in Angular 6+

### ISSUE THREAD

**Issue by lynx-r** [vMReal/digest-auth#3]
* **I'm submitting a bug**
[*] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

This lib doesn't work with recent Angular 6+ because of missed `crypto` module. You can find some discussions there https://github.com/angular/angular-cli/issues/1548.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

If you wish I can create a PR with the fix.

**Comment by vMReal** [comment]
thanks for the bug. I am sure that the problem in using the crypto module which is native only for node js. I going to replace current module on cross platform. ASAP (I hope I can find time today)

**Comment by vMReal** [comment]
I have added fixes (https://github.com/vMReal/digest-auth/pull/4) v1.0.2
