### ISSUE TITLE
lib/encryptions/cn.ts uses Node.js class Buffer which is missed in browsers

### ISSUE THREAD

**Issue by lynx-r** [vMReal/digest-auth#5]
* **I'm submitting a bug**
[* ] bug report
[ ] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

There is a bug with converting `counter` into hex string while using `generateProtectionAuth`. This line uses `Node.js` class `Buffer` https://github.com/vMReal/digest-auth/blob/95bd88ebefa967e1e6bb96ae61fe826ac43635c8/src/lib/encryptions/cn.ts#L11 which is absent in browsers. Please consider replacing it with something.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

I used a workaround (just to test if there are another errors) by replacing js code of `cn.js` with this and found that everything works:

```
    static toHex(value) {
      var arr1 = [];
      for (var n = 0, l = value.length; n < l; n ++)
      {
        var hex = Number(value.charCodeAt(n)).toString(16);
        arr1.push(hex);
      }
      return arr1.join('');
      // if (value > INT32_MAX_VALUE)
      //       return '00000000';
      //   const buf = Buffer.allocUnsafe(4);
      //   buf.writeInt32BE(value, 0);
      //   return buf.toString('hex');
    }
```

**Comment by vMReal** [comment]
Thank you. I going to fix ASAP

**Comment by vMReal** [comment]
I have fixed https://github.com/vMReal/digest-auth/pull/6
